- name: Use parted on mounted volume
  parted:
     device: /dev/sdb
     number: 1
     flags: [ lvm ]
     state: present

- name: define filesystem on mounted volume
  filesystem:
     fstype: ext2
     dev: /dev/sdb1

- name: mount to /work
  mount:
    fstype: ext2
    src: /dev/sdb1
    path: /work
    state: mounted

# Put large directories on external volume
- name: Make /work/umdir folder
  file:
    path: /work/umdir
    state: directory
    owner: root
    mode: 0755

- name: symlink umdir
  file:
    src: /work/umdir
    dest: /home/{{ username }}/umdir
    state: link
    force: yes
    owner: "{{ username }}"

# put $HOME/etc/rose-meta on external volume
- name: Make /work/etc/rose-meta folder
  file:
    path: /work/etc/rose-meta
    state: directory
    owner: root
    mode: 0755

- name: Make HOME/etc folder
  file:
    path: /home/{{ username }}/etc
    state: directory
    owner: "{{ username }}"

- name: symlink rose-meta
  file:
    src: /work/etc/rose-meta
    dest: /home/{{ username }}/etc/rose-meta
    state: link
    force: yes
    owner: "{{ username }}"

- name: Make /work/cylc-run folder
  file:
    path: /work/cylc-run
    state: directory
    owner: root
    mode: 0755

- name: symlink cylc-run
  file:
    src: /work/cylc-run
    dest: /home/{{ username }}/cylc-run
    state: link
    force: yes
    owner: "{{ username }}"

- name: Make /work/src folder
  file:
    path: /work/src
    state: directory
    owner: root
    mode: 0755

- name: symlink src
  file:
    src: /work/src
    dest: /home/{{ username }}/src
    state: link
    force: yes
    owner: "{{ username }}"

- name: Make /work/doc folder
  file:
    path: /work/doc
    state: directory
    owner: root
    mode: 0755

- name: symlink doc
  file:
    src: /work/doc
    dest: /home/{{ username }}/doc
    state: link
    force: yes
    owner: "{{ username }}"

# Download and install Xconv into $UMDIR/bin
- name: make UMDIR/bin
  file:
    path: /work/umdir/bin
    state: directory
    mode: 0755

- name: Download & install Xconv to UMDIR/bin
  unarchive:
    src: http://cms.ncas.ac.uk/documents/xconv/_downloads/xconv1.94_linux_x86_64.tar.gz
    dest: /work/umdir/bin
    remote_src: yes

- name: link xconv1.94 to xconv
  file:
    src: /work/umdir/bin/xconv1.94
    dest: /work/umdir/bin/xconv
    state: link
    force: yes

- name: link xconv1.94 to convsh
  file:
    src: /work/umdir/bin/xconv1.94
    dest: /work/umdir/bin/convsh
    state: link
    force: yes

