# Prepare the base os

# Get latest package info and install updates

- name: get updates, long running process (~5mins)
  apt:
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: upgrade packages, long running process (~5mins)
  apt:
    upgrade: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install dos2unix in case any files have Windows EOL characters
  apt:
    name: dos2unix

- name: install git
  apt:
    name: git

- name: create hashed password
  command: openssl passwd -1 {{ password }}
  register: result

- set_fact:
    hashed_password: "{{ result.stdout }}"

- name: create new user
  user:
    name: "{{ username }}"
    password: "{{ hashed_password }}"
    groups: sudo,netdev
    shell: /bin/bash

- name: create ssh key directory
  file:
    path: ssh_keys
    state: directory
  delegate_to: 127.0.0.1
  become: no

- stat:
    path: ssh_keys/id_rsa_{{ username }}.pub
  register: status
  delegate_to: 127.0.0.1
  become: no

- name: create ssh key for  "{{ username }}"
  openssh_keypair:
    path: "ssh_keys/id_rsa_{{ username }}"
    type: rsa
    size: 2048
    state: present
    force: no
  delegate_to: 127.0.0.1
  become: no

- name: copy ssh key to remote host
  copy:
    src: ssh_keys/id_rsa_{{ username }}.pub
    dest: /home/{{ username }}/.ssh/

- name: add ssh key to remote account
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', 'ssh_keys/id_rsa_{{ username }}.pub') }}"

# Download metomivms data from github
- name: download metomi-vm-files from github
  git:
    repo: https://github.com/metomi/metomi-vms.git
    dest: /home/{{ vagrant }}/metomi-vms
    force: yes
  register: git_deploy
  until: git_deploy is success
  become: yes
  become_user: "{{ username }}"

# Extend root volume using lvm to include a new physical disk
#- include: create-data-vol.yml
#  when: not local


