---
- hosts: all
  remote_user: root
  gather_facts: no
  pre_tasks:
    - name: install python2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Gather facts
      setup:





  roles:
  # configure the VM and configure user access
    - create-users
    #- remove-root-access


# equivalent to: sudo systemctl restart ssh
  handlers:
  - name: Restart ssh
    service: name=ssh state=restarted
