# first make sure /home/vagrant is readable by other users
- name: Make /home/{{ vagrant }} directory tree readable
  file:
    path: /home/{{ vagrant }}
    mode: u=rwX,g=rX,o=rX
    recurse: yes

# install NFS utils
- name: Ensure NFS utilities are installed.
  apt: 
    pkg:
    - nfs-common

- name: mount to /umshared
  mount:
    fstype: nfs
    src: "{{ nfs_internal_ip }}:/umshared"
    path: /umshared
    state: mounted
    opts: ro

- name: symlink umdir
  file:
    src: /umshared/umdir
    dest: /home/{{ vagrant }}/umdir
    state: link
    force: yes

- name: symlink umdir to user
  file:
    src: /umshared/umdir
    dest: /home/{{ username }}/umdir
    state: link
    force: yes

- name: Make HOME/etc folder
  file:
    path: /home/{{ vagrant }}/etc
    state: directory
    owner: "{{ vagrant }}"

- name: symlink rose-meta
  file:
    src: /umshared/etc/rose-meta
    dest: /home/{{ vagrant }}/etc/rose-meta
    state: link
    force: yes

- name: Make HOME/cylc-run folder
  file:
    path: /home/{{ vagrant }}/cylc-run
    state: directory
    owner: "{{ vagrant }}"

- name: symlink cylc-run prebuild directories
  file:
    src: /umshared/cylc-run
    dest: /home/{{ vagrant }}/cylc-run
    state: link
    force: yes

- name: symlink src
  file:
    src: /umshared/src
    dest: /home/{{ vagrant }}/src
    state: link
    force: yes

- name: symlink doc
  file:
    src: /umshared/doc
    dest: /home/{{ vagrant }}/doc
    state: link
    force: yes

- name: symlink source
  file:
    src: /umshared/source
    dest: /home/{{ vagrant }}/source
    state: link
    force: yes

- name: symlink Tutorials directory
  file:
    src: /umshared/Tutorials
    dest: /home/{{ vagrant }}/Tutorials
    state: link
    force: yes

- name: symlink Tutorials to user
  file:
    src: /umshared/Tutorials
    dest: /home/{{ username }}/Tutorials
    state: link
    force: yes



