# Prepare the base os

# Get latest package info and install updates

- name: get updates, long running process (~5mins)
  apt:
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install dos2unix in case any files have Windows EOL characters
  apt:
    name: dos2unix

- name: install git
  apt:
    name: git

# define users
- include: users.yml user={{ admin_username }} user_password={{ admin_password }} user_groups="sudo,netdev"
- include: users.yml user={{ vagrant }} user_password={{ vagrant }} user_groups="netdev" 
- include: users.yml user={{ username }} user_password={{ password }} user_groups="netdev" 

# Download metomivms data from github
- name: download metomi-vm-files from github
  git:
    repo: https://github.com/metomi/metomi-vms.git
    dest: /home/{{ vagrant }}/metomi-vms
    force: yes
  register: git_deploy
  until: git_deploy is success

# Extend root volume using lvm to include a new physical disk
#- include: create-data-vol.yml
#  when: not local


