#### Install UM additions

- name: Install UM dependencies
  apt:
    pkg:
    - mpich
    - libnetcdf-dev
    - libhdf5-serial-dev
    - netcdf-bin
    - libnetcdff-dev
    - libnetcdff6
    - python-numpy
    - python-dev
    - python-mock
    - zenity 
    - "{{ grib_library }}"
    
- name: Install LaTeX (long)
  apt:
    pkg:
    - texlive
    - texlive-latex-extra
    - texlive-generic-extra
    - texlive-science

- name: Add mule requirement
  copy:
    src: mule
    dest: /usr/lib/python2.7/dist-packages/mule.pth

- name: Update .profile with UMDIR/bin in PATH
  blockinfile:
    block: "{{ lookup('file', 'profile_umdir') }}"
    path: /home/{{ username }}/.profile

- name: Update .bashrc with UMDIR
  blockinfile:
    block: "{{ lookup('file', 'bashrc_umdir') }}"
    path: /home/{{ username }}/.bashrc


# Install Iris from miniconda
- block: Install Iris via conda
    - name: Download Miniconda
      get_url:
        url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        dest: /home/{{ username }}/Downloads
	mode: 0755

    - name: Run miniconda script
      shell: Miniconda3-latest-Linux-x86_64.sh -b
      become: yes
      become_user: "{{ username }}"
      args:
         executable: /bin/bash
         chdir: /home/{{ username }}/Downloads

    - name: Install via conda
      shell: PATH=~/miniconda3/bin:$PATH conda install -y -c conda-forge iris ipython
      become: yes
      become_user: "{{ username }}"
      args:
         executable: /bin/bash

    - name: Update .bashrc with python specifics
      blockinfile:
        block: "{{ lookup('file', 'bashrc_python') }}"
        path: /home/{{ username }}/.bashrc
