#### Install UM additions

- name: Install UM dependencies
  apt:
    pkg:
    - mpich
    - libnetcdf-dev
    - libhdf5-serial-dev
    - netcdf-bin
    - libnetcdff-dev
    - libnetcdff6
    - python-numpy
    - python-dev
    - python-mock
    - zenity 
    - "{{ grib_library }}"
    
- name: Install LaTeX (long)
  apt:
    pkg:
    - texlive
    - texlive-latex-extra
    - texlive-generic-extra
    - texlive-science

- name: Add mule requirement
  copy:
    src: mule
    dest: /usr/lib/python2.7/dist-packages/mule.pth

- name: make UMDIR/bin
  file:
    path: /home/{{ username }}/umdir/bin
    state: directory

- name: Download & install Xconv to UMDIR/bin
  unarchive:
    src: http://cms.ncas.ac.uk/documents/xconv/_downloads/xconv1.94_linux_x86_64.tar.gz
    dest: /home/{{ username }}/umdir/bin
    remote_src: yes

- name: link xconv1.94 to xconv
  file:
    src: /home/{{ username }}/umdir/bin/xconv1.94
    dest: /home/{{ username }}/umdir/bin/xconv
    state: link
    force: yes

- name: link xconv1.94 to convsh
  file:
    src: /home/{{ username }}/umdir/bin/xconv1.94
    dest: /home/{{ username }}/umdir/bin/convsh
    state: link
    force: yes

- name: Update .profile with UMDIR/bin in PATH
  blockinfile:
    block: "{{ lookup('file', 'bashrc_umdir') }}"
    path: /home/{{ username }}/.profile
